//! Complete HTML to PDF Conversion Example
//!
//! This example demonstrates the full HTML to PDF conversion pipeline:
//! 1. Parsing HTML from a string
//! 2. Parsing CSS from a string
//! 3. Building the layout tree
//! 4. Computing styles
//! 5. Performing layout
//! 6. Generating PDF output
//!
//! Run with: cargo run --example complete_example

use html2pdf::{
    css, html, layout, pdf,
    types::{Color, Margins, Orientation, PaperSize, Rect},
    Config, Input,
};
use std::io::Cursor;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("=== HTML2PDF Complete Example ===\n");

    // Step 1: Parse HTML from a string
    println!("Step 1: Parsing HTML...");
    let html_content = create_sample_html();
    let document = html::parse_html(&html_content)?;
    println!("  ✓ Parsed HTML document: {:?}", &document.title);

    // Step 2: Parse CSS from a string
    println!("\nStep 2: Parsing CSS...");
    let css_content = create_sample_css();
    let stylesheet = css::parse_stylesheet(&css_content)?;
    println!("  ✓ Parsed stylesheet with {} rules", stylesheet.rules.len());

    // Step 3: Create layout context with custom settings
    println!("\nStep 3: Setting up layout context...");
    let layout_ctx = layout::LayoutContext::with_page_size(PaperSize::A4, Orientation::Portrait)
        .with_margins(Margins::new(72.0, 72.0, 72.0, 72.0)); // 1 inch margins
    println!("  ✓ Page size: A4 Portrait");
    println!("  ✓ Margins: 72pt (1 inch) on all sides");

    // Step 4: Build and perform layout
    println!("\nStep 4: Building layout tree...");
    let mut engine = layout::LayoutEngine::with_context(layout_ctx.clone());
    engine.add_stylesheet(stylesheet);
    
    let layout_tree = engine.layout_document(&document)?;
    println!("  ✓ Layout tree built successfully");

    // Step 5: Collect positioned boxes
    println!("\nStep 5: Collecting positioned boxes...");
    let boxes = layout::collect_positioned_boxes(&layout_tree);
    println!("  ✓ Found {} positioned boxes", boxes.len());

    // Print some layout information
    println!("\n  Layout Tree Structure:");
    layout::print_layout_tree(&layout_tree, 1);

    // Step 6: Generate PDF
    println!("\nStep 6: Generating PDF...");
    let pdf_bytes = generate_pdf(&boxes, &layout_ctx)?;
    println!("  ✓ Generated PDF: {} bytes", pdf_bytes.len());

    // Step 7: Alternative: Use the high-level API
    println!("\nStep 7: Using high-level API...");
    let high_level_pdf = generate_with_high_level_api()?;
    println!("  ✓ Generated PDF using high-level API: {} bytes", high_level_pdf.len());

    // Write PDFs to files
    let output_path = "examples/output_complete_example.pdf";
    std::fs::write(output_path, &pdf_bytes)?;
    println!("\n  ✓ PDF written to: {}", output_path);

    let output_path2 = "examples/output_high_level_api.pdf";
    std::fs::write(output_path2, &high_level_pdf)?;
    println!("  ✓ PDF written to: {}", output_path2);

    println!("\n=== Example Complete! ===");
    println!("Open the PDF files to see the results.");

    Ok(())
}

/// Create sample HTML content with various elements
fn create_sample_html() -> String {
    r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Complete Example</title>
</head>
<body>
    <h1>HTML2PDF Complete Example</h1>
    
    <p class="intro">
        This document demonstrates the full HTML to PDF conversion pipeline.
        It includes various HTML elements and CSS styling.
    </p>
    
    <h2>Features Demonstrated</h2>
    
    <ul>
        <li>HTML5 parsing</li>
        <li>CSS styling</li>
        <li>Typography and fonts</li>
        <li>Tables</li>
        <li>Margins and padding</li>
    </ul>
    
    <h2>Sample Table</h2>
    
    <table>
        <tr>
            <th>Component</th>
            <th>Status</th>
        </tr>
        <tr>
            <td>HTML Parser</td>
            <td>Working</td>
        </tr>
        <tr>
            <td>CSS Parser</td>
            <td>Working</td>
        </tr>
        <tr>
            <td>Layout Engine</td>
            <td>Working</td>
        </tr>
        <tr>
            <td>PDF Generator</td>
            <td>Working</td>
        </tr>
    </table>
    
    <div class="highlight">
        <p>This is a highlighted section with custom styling.</p>
    </div>
    
    <p class="footer">
        Generated by html2pdf-rs - A Rust HTML to PDF converter
    </p>
</body>
</html>"#.to_string()
}

/// Create sample CSS content
fn create_sample_css() -> String {
    r#"/* Sample stylesheet for the complete example */

body {
    font-family: Helvetica, Arial, sans-serif;
    font-size: 12pt;
    line-height: 1.6;
    color: #333;
}

h1 {
    font-size: 24pt;
    color: #2c3e50;
    border-bottom: 2pt solid #3498db;
    margin-bottom: 20pt;
}

h2 {
    font-size: 16pt;
    color: #34495e;
    margin-top: 24pt;
}

p {
    margin: 12pt 0;
}

.intro {
    font-style: italic;
    color: #666;
}

ul {
    margin: 12pt 0;
    padding-left: 24pt;
}

li {
    margin: 6pt 0;
}

table {
    width: 100%;
    border-collapse: collapse;
    margin: 16pt 0;
}

th, td {
    border: 1pt solid #ddd;
    padding: 8pt;
    text-align: left;
}

th {
    background-color: #f2f2f2;
    font-weight: bold;
}

.highlight {
    background-color: #fff3cd;
    border-left: 4pt solid #ffc107;
    padding: 12pt;
    margin: 16pt 0;
}

.footer {
    margin-top: 30pt;
    padding-top: 10pt;
    border-top: 1pt solid #ddd;
    font-size: 10pt;
    color: #999;
    text-align: center;
}"#.to_string()
}

/// Generate PDF from layout boxes
fn generate_pdf(
    boxes: &[&layout::LayoutBox],
    ctx: &layout::LayoutContext,
) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
    // Create PDF writer
    let mut writer = pdf::PdfWriter::new();
    writer.set_paper_size(PaperSize::A4, Orientation::Portrait);
    writer.set_margins(ctx.margins);
    writer.init_document();
    writer.set_info(
        "HTML2PDF Complete Example",
        "HTML2PDF Example",
        "html2pdf-rs v0.1.0",
    );

    // Add fonts
    writer.add_standard_font("F1", "Helvetica");
    writer.add_standard_font("F2", "Helvetica-Bold");
    writer.add_standard_font("F3", "Times-Roman");
    writer.add_standard_font("F4", "Courier");

    // Create page content
    let page_height = ctx.page_height();
    let mut content = pdf::PageContent::new();

    // Set up initial text state
    content.save_state();
    content.set_fill_color(Color::new(51, 51, 51)); // #333

    // Render each box
    for box_ in boxes {
        render_box(box_, &mut content, page_height)?;
    }

    content.restore_state();

    // Add the page to the document
    writer.add_page(content);

    // Write to buffer
    let mut output = Cursor::new(Vec::new());
    writer.write(&mut output)?;

    Ok(output.into_inner())
}

/// Render a single layout box to PDF content
fn render_box(
    box_: &layout::LayoutBox,
    content: &mut pdf::PageContent,
    page_height: f32,
) -> Result<(), Box<dyn std::error::Error>> {
    use layout::BoxType;

    let dims = &box_.dimensions;
    let border_box = dims.border_box();

    // Convert y-coordinate to PDF system (origin at bottom-left)
    let pdf_y = page_height - border_box.y - border_box.height;

    match box_.box_type {
        BoxType::Block | BoxType::InlineBlock => {
            // Draw border if present
            if dims.border.top > 0.0
                || dims.border.right > 0.0
                || dims.border.bottom > 0.0
                || dims.border.left > 0.0
            {
                content.save_state();
                content.set_line_width(0.5);
                content.set_stroke_color(Color::new(200, 200, 200));
                content.draw_rect(Rect::new(border_box.x, pdf_y, border_box.width, border_box.height));
                content.stroke();
                content.restore_state();
            }
        }
        BoxType::TextRun => {
            if let Some(ref text) = box_.text_content {
                let trimmed = text.trim();
                if !trimmed.is_empty() {
                    content.save_state();
                    content.begin_text();
                    content.set_font("F1", 12.0);
                    content.set_fill_color(Color::new(51, 51, 51));
                    content.text_position(border_box.x, pdf_y + 10.0);
                    content.show_text(trimmed);
                    content.end_text();
                    content.restore_state();
                }
            }
        }
        BoxType::Inline => {
            // Inline containers don't render directly
        }
        BoxType::Anonymous => {
            // Anonymous boxes are for layout only
        }
        _ => {}
    }

    Ok(())
}

/// Generate PDF using the high-level convenience API
fn generate_with_high_level_api() -> Result<Vec<u8>, Box<dyn std::error::Error>> {
    // Create HTML content
    let html = r#"
        <h1>High-Level API Example</h1>
        <p>This PDF was generated using the simple high-level API.</p>
        <p>The API handles all the details: parsing, layout, and PDF generation.</p>
        <table>
            <tr><th>Step</th><th>Description</th></tr>
            <tr><td>1</td><td>Parse HTML</td></tr>
            <tr><td>2</td><td>Parse CSS</td></tr>
            <tr><td>3</td><td>Build Layout</td></tr>
            <tr><td>4</td><td>Generate PDF</td></tr>
        </table>
    "#;

    // Create input
    let input = Input::Html(html.to_string());

    // Create configuration with custom settings
    let config = Config {
        paper_size: PaperSize::A4,
        orientation: Orientation::Portrait,
        margins: Margins::all(72.0),
        page_width: None,
        page_height: None,
        header: None,
        footer: Some("<p>Page from high-level API</p>".to_string()),
        user_stylesheets: vec![create_sample_css()],
        base_url: None,
        timeout_seconds: 30,
        debug_layout: false,
    };

    // Convert to PDF
    let pdf_bytes = html2pdf::html_to_pdf_from_input(&input, &config)?;

    Ok(pdf_bytes)
}
